name: sample1

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy to tomcat  
      run: curl -v -u tomcat:tomcat -T /home/runner/work/newrepo1/newrepo1/webapp/target/webapp.war 'http://52.221.188.237:8080//manager/text/deploy?path=/webapp'
